### ISSUE TITLE
Test cases are failing !!!

### ISSUE THREAD

**Issue by harshadyeola** [AniketDha/AniRT#6]
``` bash
root@ubuntu-web:~/AniRT# 
root@ubuntu-web:~/AniRT# python3 -m unittest discover 
Category Name already exists or default value used
no such table: category_tab
.category Name Invalid
no such table: category_tab
.FE...FCategory Name already exists or default value used
no such table: category_tab
.category Name Invalid
no such table: category_tab
..no such table: post_tab
FSearch Keyword is empty
.Integer Value is provided
.Command is not valid no such table: post_tab
.Command is not valid no such table: post_tab
.
======================================================================
ERROR: test_list_empty (test_cat_list.Test_listcat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 161, in handle
    callable_obj(*args, **kwargs)
TypeError: 'tuple' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/AniRT/test_cat_list.py", line 21, in test_list_empty
    self.assertRaises("List is empty",listCat())
  File "/usr/lib/python3.4/unittest/case.py", line 701, in assertRaises
    return context.handle('assertRaises', callableObj, args, kwargs)
  File "/usr/lib/python3.4/unittest/case.py", line 161, in handle
    callable_obj(*args, **kwargs)
  File "/usr/lib/python3.4/unittest/case.py", line 181, in __exit__
    if not issubclass(exc_type, self.expected):
TypeError: issubclass() arg 2 must be a class or tuple of classes

======================================================================
FAIL: test_list (test_cat_list.Test_listcat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/AniRT/test_cat_list.py", line 19, in test_list
    self.assertEqual(listCat(),None)
AssertionError: ('List is empty', OperationalError('no such table: category_tab',)) != None

======================================================================
FAIL: test_some_catName_present (test_create_cat.MyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/AniRT/test_create_cat.py", line 32, in test_some_catName_present
    self.assertEqual(createCat(self.catName), 'UNIQUE constraint failed: category_tab.categ')
AssertionError: 'no such table: category_tab' != 'UNIQUE constraint failed: category_tab.categ'
- no such table: category_tab
+ UNIQUE constraint failed: category_tab.categ


======================================================================
FAIL: test_cat_present1 (test_insert_post.test_insert_pos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/AniRT/test_insert_post.py", line 39, in test_cat_present1
    self.assertEqual(insertPost(self.pNam, self.pCont, self.cat), "Invalid Post Name")
AssertionError: None != 'Invalid Post Name'

----------------------------------------------------------------------
Ran 16 tests in 0.020s

FAILED (failures=3, errors=1)
root@ubuntu-web:~/AniRT# 
```

**Comment by AniketDha** [comment]
Sir, assumption is that user should first add few records in the database...
I wrote test cases separately..
@ubuntu:~/Desktop/TestCases$ python3 -m unittest discover
Category Name already exists or default value used
For Help - ./blog.py --help
.category Name Invalid
For Help - ./blog.py --help
.update post_tab set cati= 7 where pid= 1
.update post_tab set cati= 0 where pid= 0
.update post_tab set cati= 2 where pid= 0
........Post Name is already exists
.Category List
ID:0   Name:default
ID:1   Name:asdf
ID:2   Name:def
ID:6   Name:AnyNamy1
ID:7   Name:list
.Category List
ID:0   Name:default
ID:1   Name:asdf
ID:2   Name:def
ID:6   Name:AnyNamy1
ID:7   Name:list
.Search Keyword is empty
.Integer Value is provided
..Post Name: Post no 123
Post Content: Content Good

## .

Ran 19 tests in 0.086s

OK

**Comment by harshadyeola** [comment]
``` bash
root@ubuntu-web:~/AniRT# python3 -m unittest discover 
Post submited with category  asdf
.category Name Invalid
For Help - ./blog.py --help
.Category List
ID:0   Name:default
ID:1   Name:asdf
.Category List
ID:0   Name:default
ID:1   Name:asdf
.....Category Name already exists or default value used
For Help - ./blog.py --help
.category Name Invalid
For Help - ./blog.py --help
..FSearch Keyword is empty
.Integer Value is provided
..Post Name: Post no 123
Post Content: Content Good
.
======================================================================
FAIL: test_cat_present1 (test_insert_post.test_insert_pos)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/AniRT/test_insert_post.py", line 39, in test_cat_present1
    self.assertEqual(insertPost(self.pNam, self.pCont, self.cat), "Invalid Post Name")
AssertionError: 'Post Updated' != 'Invalid Post Name'
- Post Updated
+ Invalid Post Name


----------------------------------------------------------------------
Ran 16 tests in 0.033s

FAILED (failures=1)
root@ubuntu-web:~/AniRT# 
```
